name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # เมื่อมีการ push ไปที่ branch main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # ใช้ DockerHub username จาก Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # ใช้ DockerHub password จาก Secrets

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-simple-app .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-simple-app

    - name: SSH into EC2 instance and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd /path/to/your/app
          docker-compose down
          docker-compose up -d
